name: YarnCI

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.18.2 ] # Only run the 14.18.x build
    steps:
      - name: Use Node.js $
        uses: actions/checkout@v1
      - name: install node ${{matrix.node-version}}
        uses: actions/setup-node@v2
      - name: package data
        run: |
            npm install -g yarn
            yarn
            yarn docs:build
      - name: Deploy to Server  # rsync推送文件
        uses: AEnterprise/rsync-deploy@v1.0  # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}   # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc'   # rsync参数，排除.pyc文件
          SERVER_PORT:  ${{ secrets.SSH_PORT }}  # SSH端口
          FOLDER: ./docs/.vuepress/dist/*  # 要推送的文件夹，路径相对于代码仓库根目录
          SERVER_IP: ${{ secrets.SSH_HOST }}  # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.SSH_USERNAME }}  # 引用配置，服务器登录名
          SERVER_DESTINATION: /www/docs/   # 部署到目标文件夹
