name: RELEASE

on:
    push:
      branches:
        - main
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    task1:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@main
        - uses: borales/actions-yarn@v3.0.0
          with:
            cmd: install
        - uses: borales/actions-yarn@v3.0.0
          with:
            run: yarn docs:build
