name: RELEASE

on:
    push:
      branches:
        - main
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    task1:
      runs-on: ubuntu-latest

      steps:
        - name: CopyCodeToAnBuildContainer
          uses: actions/checkout@v3

        - name: Independences
          uses: borales/actions-yarn@v3.0.0
          run:  yarn install

        - name: toPackage
          uses: borales/actions-yarn@v3.0.0
          run: yarn docs:build

