name: RELEASE

on:
    push:
      branches:
        - main
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
    task1:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Setup node
          uses: borales/actions-yarn@v1
          with:
            node-version: 14.18.2
            cache: npm

        - name: Install
          run: yarn

        - name: Build
          run: yarn docs:build
